[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "export SHELL=/bin/bash && curl -fsSL https://get.pnpm.io/install.sh | SHELL=/bin/bash sh -",
  "$HOME/.local/share/pnpm/pnpm install"
]

[phases.build]
cmds = [
  "cd packages/shared && $HOME/.local/share/pnpm/pnpm build",
  "cd packages/database && $HOME/.local/share/pnpm/pnpm build", 
  "cd apps/websocket-server && $HOME/.local/share/pnpm/pnpm build"
]

[start]
cmd = "cd apps/websocket-server && $HOME/.local/share/pnpm/pnpm start" 