[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "export SHELL=/bin/bash && curl -fsSL https://get.pnpm.io/install.sh | SHELL=/bin/bash sh -",
  "$HOME/.local/share/pnpm/pnpm install"
]

[phases.build]
cmds = [
  "$HOME/.local/share/pnpm/pnpm run build"
]

[start]
cmd = "cd apps/websocket-server && $HOME/.local/share/pnpm/pnpm start" 