[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "export SHELL=/bin/bash && curl -fsSL https://get.pnpm.io/install.sh | SHELL=/bin/bash sh -",
  "$HOME/.local/share/pnpm/pnpm install"
]

[phases.build]
cmds = [
  "$HOME/.local/share/pnpm/pnpm run build --filter=@shipvibes/websocket-server...",
  "echo '=== Checking websocket-server dist folder ===' && ls -la apps/websocket-server/",
  "echo '=== Checking if dist/index.js exists ===' && ls -la apps/websocket-server/dist/ || echo 'dist folder not found'"
]

[start]
cmd = "cd apps/websocket-server && echo '=== Current directory ===' && pwd && echo '=== Files in current directory ===' && ls -la && echo '=== Contents of dist folder ===' && ls -la dist/ && echo '=== Starting server ===' && $HOME/.local/share/pnpm/pnpm start" 