[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "export SHELL=/bin/bash",
  "curl -fsSL https://get.pnpm.io/install.sh | SHELL=/bin/bash sh -",
  "export PATH=\"$HOME/.local/share/pnpm:$PATH\"",
  "cd ../..",
  "$HOME/.local/share/pnpm/pnpm install",
  "cd apps/websocket-server"
]

[phases.build]
cmds = [
  "cd apps/websocket-server",
  "$HOME/.local/share/pnpm/pnpm build"
]

[start]
cmd = "cd apps/websocket-server && $HOME/.local/share/pnpm/pnpm start" 