[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "export SHELL=/bin/bash && curl -fsSL https://get.pnpm.io/install.sh | SHELL=/bin/bash sh -",
  "cd ../.. && $HOME/.local/share/pnpm/pnpm install"
]

[phases.build]
cmds = [
  "cd ../.. && cd apps/websocket-server && $HOME/.local/share/pnpm/pnpm build"
]

[start]
cmd = "cd ../.. && cd apps/websocket-server && $HOME/.local/share/pnpm/pnpm start" 